# AI Investment Decision Support System

## Notebook 01 – Stock Data Download

This notebook downloads historical stock price data for Reliance Industries Ltd. using the Yahoo Finance API (`yfinance`) and stores it locally for further analysis.

In [1]:
import pandas as pd
import yfinance as yf

In [2]:
ticker = "RELIANCE.NS"

stock = yf.download(
    ticker,
    start="2015-01-01",
    end="2024-12-31",
    auto_adjust=False
)

[*********************100%***********************]  1 of 1 completed

In [3]:
stock.head()

Price,Adj Close,Close,High,Low,Open,Volume
Ticker,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS
Date,,,,,,
2015-01-01,189.125381,202.959000,203.896194,201.987518,202.593277,2963643
2015-01-02,188.624832,202.421829,204.821960,202.136108,203.004715,7331366
2015-01-05,186.558685,200.204575,203.644760,199.804550,202.296112,10103941
2015-01-06,178.091797,191.118393,199.553116,190.181198,198.867371,18627980
2015-01-07,181.968475,195.278610,196.307236,191.324127,191.346985,20720312

In [4]:
stock.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 2466 entries, 2015-01-01 to 2024-12-30
Data columns (total 6 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   (Adj Close, RELIANCE.NS)  2466 non-null   float64
 1   (Close, RELIANCE.NS)      2466 non-null   float64
 2   (High, RELIANCE.NS)       2466 non-null   float64
 3   (Low, RELIANCE.NS)        2466 non-null   float64
 4   (Open, RELIANCE.NS)       2466 non-null   float64
 5   (Volume, RELIANCE.NS)     2466 non-null   int64
dtypes: float64(5), int64(1)
memory usage: 134.9 KB

In [5]:
stock.to_csv("../data/raw/reliance.csv")

In [6]:
saved_stock = pd.read_csv("../data/raw/reliance.csv")

saved_stock.head()

,Price,Adj Close,Close,High,Low,Open,Volume
0,Ticker,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS
1,Date,NaN,NaN,NaN,NaN,NaN,NaN
2,2015-01-01,189.12538146972656,202.95899963378906,203.8961944580078,201.98751831054688,202.59327697753906,2963643
3,2015-01-02,188.6248321533203,202.4218292236328,204.82196044921875,202.1361083984375,203.0047149658203,7331366
4,2015-01-05,186.55868530273438,200.20457458496094,203.64476013183594,199.80455017089844,202.29611206054688,10103941

In [7]:
saved_stock.shape

(2468, 7)

In [8]:
print("Reliance stock data downloaded and saved successfully!")

Reliance stock data downloaded and saved successfully!