# AI Investment Decision Support System

## Notebook 01 - Stock Data Download

This notebook downloads historical stock price data for Reliance Industries and saves it for further analysis.

In [22]:
import pandas as pd
import yfinance as yf

In [23]:
ticker = "RELIANCE.NS"

stock = yf.download(
    ticker,
    start="2015-01-01",
    end="2024-12-31",
    auto_adjust=False
)

[*********************100%***********************]  1 of 1 completed

In [25]:
stock.columns = stock.columns.get_level_values(0)

stock.columns

Index(['Adj Close', 'Close', 'High', 'Low', 'Open', 'Volume'], dtype='str', name='Price')

In [26]:
stock = stock.reset_index()

stock.head()

Price,Date,Adj Close,Close,High,Low,Open,Volume
0,2015-01-01,189.125381,202.959000,203.896194,201.987518,202.593277,2963643
1,2015-01-02,188.624832,202.421829,204.821960,202.136108,203.004715,7331366
2,2015-01-05,186.558685,200.204575,203.644760,199.804550,202.296112,10103941
3,2015-01-06,178.091797,191.118393,199.553116,190.181198,198.867371,18627980
4,2015-01-07,181.968475,195.278610,196.307236,191.324127,191.346985,20720312

In [27]:
print(stock.columns.tolist())

['Date', 'Adj Close', 'Close', 'High', 'Low', 'Open', 'Volume']

In [28]:
stock.to_csv("../data/raw/reliance.csv", index=False)

print("Reliance stock data saved successfully!")

Reliance stock data saved successfully!

In [29]:
saved_stock = pd.read_csv("../data/raw/reliance.csv")

saved_stock.head()

,Date,Adj Close,Close,High,Low,Open,Volume
0,2015-01-01,189.125381,202.959000,203.896194,201.987518,202.593277,2963643
1,2015-01-02,188.624832,202.421829,204.821960,202.136108,203.004715,7331366
2,2015-01-05,186.558685,200.204575,203.644760,199.804550,202.296112,10103941
3,2015-01-06,178.091797,191.118393,199.553116,190.181198,198.867371,18627980
4,2015-01-07,181.968475,195.278610,196.307236,191.324127,191.346985,20720312

In [30]:
print(saved_stock.columns.tolist())

['Date', 'Adj Close', 'Close', 'High', 'Low', 'Open', 'Volume']

In [31]:
print(saved_stock.shape)

(2466, 7)

In [32]:
saved_stock.info()

<class 'pandas.DataFrame'>
RangeIndex: 2466 entries, 0 to 2465
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       2466 non-null   str
 1   Adj Close  2466 non-null   float64
 2   Close      2466 non-null   float64
 3   High       2466 non-null   float64
 4   Low        2466 non-null   float64
 5   Open       2466 non-null   float64
 6   Volume     2466 non-null   int64
dtypes: float64(5), int64(1), str(1)
memory usage: 135.0 KB