# Advanced Feature Engineering

## Objectives

Enhance the dataset by creating additional technical indicators that may improve machine learning model performance.

In [1]:
import numpy as np
import pandas as pd

In [2]:
stock = pd.read_csv(
    "../data/processed/reliance_features.csv",
    parse_dates=["Date"]
)

stock.set_index("Date", inplace=True)

stock.head()

,Adj Close,Close,High,Low,Open,Volume,Daily_Return,Log_Return,Trading_Range,Price_Change,Volatility20,MA20,MA50,MA200,EMA20,Target
Date,,,,,,,,,,,,,,,,
2015-10-21,205.980789,218.296936,222.822876,217.839767,218.411224,14404450,-0.001777,-0.001779,4.983109,-0.114288,0.018993,203.392169,203.055238,206.833089,206.858732,1
2015-10-23,206.120972,218.445511,222.422867,215.131058,220.342758,12153422,0.000681,0.000680,7.291809,-1.897247,0.016707,204.623661,202.994663,206.910522,207.962235,0
2015-10-26,203.360199,215.519653,220.125595,215.165344,219.874161,10938775,-0.013394,-0.013485,4.960251,-4.354507,0.017261,205.680859,202.888829,206.976011,208.681989,0
2015-10-27,202.648392,214.765320,216.753998,214.273865,214.593887,11601798,-0.003500,-0.003506,2.480133,0.171432,0.016713,206.848918,202.873514,207.048814,209.261354,0
2015-10-28,202.087601,214.171005,215.988251,212.559494,214.159576,11958727,-0.002767,-0.002771,3.428757,0.011429,0.016686,208.022693,202.889972,207.164078,209.728939,1

In [3]:
delta = stock["Close"].diff()

gain = delta.where(delta > 0, 0)
loss = -delta.where(delta < 0, 0)

avg_gain = gain.rolling(14).mean()
avg_loss = loss.rolling(14).mean()

rs = avg_gain / avg_loss

stock["RSI"] = 100 - (100 / (1 + rs))

In [4]:
ema12 = stock["Close"].ewm(span=12, adjust=False).mean()
ema26 = stock["Close"].ewm(span=26, adjust=False).mean()

stock["MACD"] = ema12 - ema26

stock["MACD_Signal"] = stock["MACD"].ewm(
    span=9,
    adjust=False
).mean()

In [5]:
rolling_mean = stock["Close"].rolling(20).mean()
rolling_std = stock["Close"].rolling(20).std()

stock["BB_Upper"] = rolling_mean + (2 * rolling_std)
stock["BB_Lower"] = rolling_mean - (2 * rolling_std)

stock["BB_Width"] = stock["BB_Upper"] - stock["BB_Lower"]

In [6]:
stock["Momentum10"] = (
    stock["Close"] - stock["Close"].shift(10)
)

In [7]:
stock = stock.dropna()

In [8]:
stock.columns.tolist()

['Adj Close',
 'Close',
 'High',
 'Low',
 'Open',
 'Volume',
 'Daily_Return',
 'Log_Return',
 'Trading_Range',
 'Price_Change',
 'Volatility20',
 'MA20',
 'MA50',
 'MA200',
 'EMA20',
 'Target',
 'RSI',
 'MACD',
 'MACD_Signal',
 'BB_Upper',
 'BB_Lower',
 'BB_Width',
 'Momentum10']

In [9]:
stock.to_csv("../data/processed/reliance_advanced_features.csv")

In [10]:
advanced = pd.read_csv(
    "../data/processed/reliance_advanced_features.csv"
)

advanced.head()

,Date,Adj Close,Close,High,Low,Open,Volume,Daily_Return,Log_Return,Trading_Range,...,MA200,EMA20,Target,RSI,MACD,MACD_Signal,BB_Upper,BB_Lower,BB_Width,Momentum10
0,2015-11-20,204.222931,216.433975,217.794052,211.565155,213.496689,11304265,0.012945,0.012862,6.228897,...,208.368368,213.480029,1,51.550482,-1.221252,-1.031852,221.865864,209.212293,12.653571,-1.017197
1,2015-11-23,205.711151,218.011200,218.959824,216.285400,217.154022,10499517,0.007287,0.007261,2.674423,...,208.396198,213.911569,1,51.601790,-0.842501,-0.993982,221.826597,209.222987,12.603610,3.920197
2,2015-11-24,208.720001,221.199936,222.091415,217.394028,217.839767,14806176,0.014626,0.014521,4.697388,...,208.456144,214.605699,1,52.071310,-0.281785,-0.851542,222.342142,208.982884,13.359258,3.497314
3,2015-11-26,213.238602,225.988754,226.743088,221.325668,221.954269,23805828,0.021649,0.021418,5.417419,...,208.548263,215.689800,0,55.250916,0.542747,-0.572684,224.304350,208.067586,16.236764,6.263168
4,2015-11-27,211.168030,223.794357,226.868805,222.662872,226.068756,10891864,-0.009710,-0.009758,4.205933,...,208.595637,216.461662,0,57.009350,1.007512,-0.256645,225.401663,207.873177,17.528486,12.869232

## Conclusion

### New Features Added

- RSI (14)
- MACD
- MACD Signal
- Bollinger Bands
- Bollinger Band Width
- Momentum (10)

These indicators capture trend, momentum, and volatility, providing richer information for machine learning models.